export const GET_ASSESSMENTS_START = "GET_ASSESSMENTS_START";
export const GET_ASSESSMENTS_SUCCESS = "GET_ASSESSMENTS_SUCCESS";
export const GET_ASSESSMENTS_FAIL = "GET_ASSESSMENTS_FAIL";

export const CREATE_ASSESSMENT_START = "CREATE_ASSESSMENT_START";
export const CREATE_ASSESSMENT_SUCCESS = "CREATE_ASSESSMENT_SUCCESS";
export const CREATE_ASSESSMENT_FAIL = "CREATE_ASSESSMENT_FAIL";


export const SET_CURRENT_ASSESSMENT_START = "SET_CURRENT_ASSESSMENT_START";
export const SET_CURRENT_ASSESSMENT_SUCCESS = "SET_CURRENT_ASSESSMENT_SUCCESS";
export const SET_CURRENT_ASSESSMENT_FAIL = "SET_CURRENT_ASSESSMENT_FAIL";
